[tool.poetry]
name = "kurs-rabota-4"
version = "0.1.0"
description = ""
authors = ["Leonid Petrov <leonidpetrov637@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
